apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-watcherv2
  labels:
    app: eventhub-watcherv2
spec:
  selector:
    matchLabels:
      app: eventhub-watcherv2
  template:
    metadata:
      labels:
        app: eventhub-watcherv2
    spec:
      containers:
      - name: eventhub-watcherv2
        image: yaronpr/custom_metrics_emitter:latest
        env:
        - name: EventHubConnectionString
          valueFrom:
            secretKeyRef:
              name: secrets-eventhub-watcherv2
              key: eventhub-connectionstring
        - name: CheckPointConnectionString
          valueFrom:
            secretKeyRef:
              name: secrets-eventhub-watcherv2
              key: checkpoint-connectionstring
        - name: EventHubName
          value: step1v2
        - name: EventHubConsumerGroup
          value: $Default
        - name: CheckPointContainer
          value: step1checkpoint
      nodeSelector:
        "gen3": "yes"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-eventhub-watcherv2
  labels:
    app: eventhub-watcherv2
data:
  eventhub-connectionstring: RW5kcG9pbnQ9c2I6Ly9wNHByZW1pdW1ldmVudGh1Yi5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PUw4SmRpbGFrTlhpOTRObFpURmVjU2Q0VlpEM2ErMC82YnZMRmRsNExqUXc9
  checkpoint-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0djJpbmNvbWluZ2V2ZW50cztBY2NvdW50S2V5PTZwRlJtOW5YMkt0d2NNUFVVMExRY1FkQUtQb1U3VGdjWVlGOW5PVkt2ZkxmSXRZdWFzd2ZWQ1RqQ1VpVURyMEV3L1JSQi9zVk1GVmpTR0hLUERudUdRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
---
apiVersion: v1
kind: Service
metadata:
  name: eventhub-watcherv2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: eventhub-watcherv2